package com.foxy.patreon.validator.entity;

import java.time.Instant;

import software.amazon.awssdk.enhanced.dynamodb.extensions.annotations.DynamoDbAutoGeneratedTimestampAttribute;
import software.amazon.awssdk.enhanced.dynamodb.mapper.UpdateBehavior;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbAttribute;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbBean;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbPartitionKey;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbSecondaryPartitionKey;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbSecondarySortKey;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbSortKey;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbUpdateBehavior;

@DynamoDbBean
public class PatronEntity {

    private String discordId;
   
    private String patronId;

    private String characterName;
    private String status;
    private Instant creationDate;

    @DynamoDbAttribute("DiscordId")
    public String getDiscordId() {
        return discordId;
    }
    public void setDiscordId(String discordId) {
        this.discordId = discordId;
    }
    @DynamoDbPartitionKey
    @DynamoDbAttribute("PatronId")
    public String getPatronId() {
        return patronId;
    }
    public void setPatronId(String patronId) {
        this.patronId = patronId;
    }
    @DynamoDbAttribute("CharacterName")
    @DynamoDbSecondaryPartitionKey(indexNames={"characterNameIndex"})
    public String getCharacterName() {
        return characterName;
    }
    public void setCharacterName(String characterName) {
        this.characterName = characterName;
    }
    @DynamoDbAttribute("Status")
    @DynamoDbSecondaryPartitionKey(indexNames = {"statusIndex"})
    public String getStatus() {
        return status;
    }
    public void setStatus(String status) {
        this.status = status;
    }

    @DynamoDbSortKey
    @DynamoDbAutoGeneratedTimestampAttribute
    @DynamoDbAttribute("CreationDate")
    @DynamoDbSecondarySortKey(indexNames = {"characterNameIndex","statusIndex"})
    @DynamoDbUpdateBehavior(UpdateBehavior.WRITE_IF_NOT_EXISTS)
    public Instant getCreationDate() {
        return creationDate;
    }
    public void setCreationDate(Instant date) {
        this.creationDate = date;
    }
    
}
