package com.foxy.patreon.validator;

import java.net.URI;
import java.net.URISyntaxException;

import org.springframework.beans.factory.annotation.Value;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

import com.amazonaws.auth.AWSCredentials;
import com.amazonaws.auth.BasicAWSCredentials;

import software.amazon.awssdk.enhanced.dynamodb.DynamoDbEnhancedClient;
import software.amazon.awssdk.enhanced.dynamodb.extensions.AutoGeneratedTimestampRecordExtension;
import software.amazon.awssdk.regions.Region;
import software.amazon.awssdk.services.dynamodb.DynamoDbClient;

@Configuration
public class DynamoDBConfig {

    @Value("${amazon.dynamodb.endpoint}")
    private String amazonDynamoDBEndpoint;

    @Value("${amazon.aws.accesskey}")
    private String amazonAWSAccessKey;

    @Value("${amazon.aws.secretkey}")
    private String amazonAWSSecretKey;
    @Value("${amazon.aws.region}")
    private String amazonAWSRegion;
    @Bean
    public DynamoDbClient amazonDynamoDB() throws URISyntaxException {
        // AmazonDynamoDB amazonDynamoDB 
        var builder
          = DynamoDbClient.builder().region(Region.of(amazonAWSRegion)).endpointOverride(new URI(amazonDynamoDBEndpoint));
        var amazonDynamoDB = builder.build();

        
        return amazonDynamoDB;
    }
@Bean
public DynamoDbEnhancedClient enhancedClient() throws URISyntaxException{
    return DynamoDbEnhancedClient.builder().dynamoDbClient(amazonDynamoDB())
    .extensions(AutoGeneratedTimestampRecordExtension.create())
    .build();
}
    @Bean
    public AWSCredentials amazonAWSCredentials() {
        return new BasicAWSCredentials(
          amazonAWSAccessKey, amazonAWSSecretKey);
    }
}